# CircleCI build config to test the Google Coud Platform CLI orb
# published by CircleCI

version: 2.1

orbs:
  gcp-cli: iynere/gcp-cli@dev:alpha

jobs:
  install:
    executor: gcp-cli/default
    steps:
      # test orb commands
      - gcp-cli/install
      - gcp-cli/initialize:
      - run: gcloud -v

workflows:
  install_and_initialize_gcloud:
    jobs:
      # test orb commands
      - install
      # test orb jobs
      - gcp-cli/install_and_initialize_cli:
          requires:
            - install
      - gcp-cli/use_google_image_and_initialize_cli:
          requires:
            - gcp-cli/install_and_initialize_cli
