version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@dev:alpha
  orb-tools: circleci/orb-tools@8.3.0

executors:
  cli:
    resource_class: small
    docker:
      - image: circleci/circleci-cli
  lint-condo:
    resource_class: small
    docker:
      - image: singapore/lint-condo
  node:
    resource_class: small
    docker:
      - image: circleci/node

jobs:
  install:
    executor: gcp-cli/default
    steps:
      # test orb commands
      - gcp-cli/install
      - gcp-cli/initialize
      - run: gcloud -v

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [install_initialize-master, google-image_install_initialize-master]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: circleci/gcp-cli
          context: orb-publishing
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          ssh-fingerprints: 44:89:7a:9b:65:2e:04:1f:01:88:1a:b7:03:28:5e:09
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          context: orb-publishing
          ssh-fingerprints: 44:89:7a:9b:65:2e:04:1f:01:88:1a:b7:03:28:5e:09
          tag: master
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      # triggered by non-master branch commits
      - install:
          name: install-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-dev
          requires:
            - install-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - gcp-cli/use_google_image_and_initialize_cli:
          name: google-image_install_initialize-dev
          context: orb-publishing
          requires:
            - install-dev
          filters: *integration-dev_filters

      # triggered by master branch commits
      - install:
          name: install-master
          context: orb-publishing
          filters: *integration-master_filters

      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-master
          requires:
            - install-master
          context: orb-publishing
          filters: *integration-master_filters

      - gcp-cli/use_google_image_and_initialize_cli:
          name: google-image_install_initialize-master
          context: orb-publishing
          requires:
            - install-master
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/gcp-cli
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          context: orb-publishing
          orb-name: circleci/gcp-cli
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          context: orb-publishing
          orb-name: circleci/gcp-cli
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
