version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@dev:alpha
  orb-tools: circleci/orb-tools@8.3.0

commands:
  install-latest:
    steps:
      - checkout

      # test orb commands
      - gcp-cli/install
      - gcp-cli/initialize

  install-versioned:
    steps:
      - checkout

      # test orb commands
      - gcp-cli/install:
          use-latest: false
          sdk-version: 224.0.0
          install-dir: /usr/local/bin

      - gcp-cli/initialize

jobs:
  # default executor
  install-default-latest:
    executor: gcp-cli/default
    steps:
      - install-latest

  install-default-versioned:
    executor: gcp-cli/default
    steps:
      - install-versioned

  # google cloud image
  install-google-latest:
    executor: gcp-cli/google
    steps:
      - install-latest

  install-google-versioned:
    executor: gcp-cli/google
    steps:
      - install-versioned

  # machine executor
  install-machine-latest:
    executor: gcp-cli/machine
    steps:
      - install-latest

  install-machine-versioned:
    executor: gcp-cli/machine
    steps:
      - install-versioned

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

install-initialize_requires-dev: &install-initialize_requires-dev
  [install-default-latest-dev, install-default-versioned-dev, install-google-latest-dev, install-google-versioned-dev, install-machine-latest-dev, install-machine-versioned-dev]

install-initialize_requires-master: &install-initialize_requires-master
  [install-default-latest-master, install-default-versioned-master, install-google-latest-master, install-google-versioned-master, install-machine-latest-master, install-machine-versioned-master]

prod-deploy_requires: &prod-deploy_requires
  [install_initialize-default-master, install_initialize-google-master, install_initialize-machine-master]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: circleci/gcp-cli
          context: orb-publishing
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          ssh-fingerprints: 44:89:7a:9b:65:2e:04:1f:01:88:1a:b7:03:28:5e:09
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          context: orb-publishing
          ssh-fingerprints: 44:89:7a:9b:65:2e:04:1f:01:88:1a:b7:03:28:5e:09
          tag: master
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      # triggered by non-master branch commits
      # run all commands with all executors
      - install-default-latest:
          name: install-default-latest-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - install-default-versioned:
          name: install-default-versioned-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - install-google-latest:
          name: install-google-latest-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - install-google-versioned:
          name: install-google-versioned-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - install-machine-latest:
          name: install-machine-latest-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - install-machine-versioned:
          name: install-machine-versioned-dev
          context: orb-publishing
          filters: *integration-dev_filters

      # run job with all executors
      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-default-dev
          context: orb-publishing
          filters: *integration-dev_filters
          requires: *install-initialize_requires-dev

      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-google-dev
          executor: gcp-cli/google
          context: orb-publishing
          filters: *integration-dev_filters
          requires: *install-initialize_requires-dev

      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-machine-dev
          executor: gcp-cli/machine
          context: orb-publishing
          filters: *integration-dev_filters
          requires: *install-initialize_requires-dev

      # triggered by master branch commits
      # run all commands with all executors
      - install-default-latest:
          name: install-default-latest-master
          context: orb-publishing
          filters: *integration-master_filters

      - install-default-versioned:
          name: install-default-versioned-master
          context: orb-publishing
          filters: *integration-master_filters

      - install-google-latest:
          name: install-google-latest-master
          context: orb-publishing
          filters: *integration-master_filters

      - install-google-versioned:
          name: install-google-versioned-master
          context: orb-publishing
          filters: *integration-master_filters

      - install-machine-latest:
          name: install-machine-latest-master
          context: orb-publishing
          filters: *integration-master_filters

      - install-machine-versioned:
          name: install-machine-versioned-master
          context: orb-publishing
          filters: *integration-master_filters

      # run job with all executors
      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-default-master
          context: orb-publishing
          filters: *integration-master_filters
          requires: *install-initialize_requires-master

      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-google-master
          executor: gcp-cli/google
          context: orb-publishing
          filters: *integration-master_filters
          requires: *install-initialize_requires-master

      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-machine-master
          executor: gcp-cli/machine
          context: orb-publishing
          filters: *integration-master_filters
          requires: *install-initialize_requires-master

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/gcp-cli
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          context: orb-publishing
          orb-name: circleci/gcp-cli
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          context: orb-publishing
          orb-name: circleci/gcp-cli
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
