version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@dev:alpha

executors:
  cli:
    resource_class: small
    docker:
      - image: circleci/circleci-cli
  lint-condo:
    resource_class: small
    docker:
      - image: singapore/lint-condo
  node:
    resource_class: small
    docker:
      - image: circleci/node

jobs:
  lint:
    executor: lint-condo
    steps:
      - checkout
      - run: yamllint .

  validate:
    executor: cli
    steps:
      - checkout
      - run: circleci orb validate src/@orb.yml

  publish-dev:
    executor: cli
    steps:
      - checkout

      - run:
          name: publish dev versions
          command: |
            # for integration testing
            circleci orb publish src/@orb.yml circleci/gcp-cli@dev:alpha --token $CIRCLE_TOKEN

            # for transparency
            circleci orb publish src/@orb.yml circleci/gcp-cli@dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN

            # for potentially promoting to prod
            circleci orb publish src/@orb.yml circleci/gcp-cli@dev:${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN

  trigger-integration:
    executor: node
    parameters:
      tag:
        type: enum
        default: "integration"
        enum: ["integration", master]
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "44:89:7a:9b:65:2e:04:1f:01:88:1a:b7:03:28:5e:09"

      - run:
          name: git config
          command: |
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
            git config --global user.name "$CIRCLE_USERNAME"

      - run: |
          INTEGRATION_TAG=<<parameters.tag>>-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
          git tag $INTEGRATION_TAG
          git push origin $INTEGRATION_TAG

  install:
    executor: gcp-cli/default
    steps:
      # test orb commands
      - gcp-cli/install
      - gcp-cli/initialize
      - run: gcloud -v

  dev-promote-prod:
    executor: cli
    steps:
      - checkout
      - run: circleci orb publish promote circleci/gcp-cli@dev:${CIRCLE_SHA1:0:7} patch --token $CIRCLE_TOKEN

workflows:
  validate_unit-test_dev-deploy:
    jobs:
      - lint

      - validate:
          requires:
            - lint

      - publish-dev:
          requires:
            - validate
          context: orb-publishing

      - trigger-integration:
          name: trigger-integration-dev
          requires:
            - publish-dev
          filters:
            branches:
              ignore: master

      - trigger-integration:
          name: trigger-integration-master
          tag: master
          requires:
            - publish-dev
          filters:
            branches:
              only: master

  integration_test-prod_deploy:
    jobs:
      # test orb commands
      - install:
          name: install-dev
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /integration-.*/

      - install:
          name: install-master
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/

      # test orb jobs
      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-dev
          requires:
            - install-dev
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /integration-.*/

      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-master
          requires:
            - install-master
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/

      - gcp-cli/use_google_image_and_initialize_cli:
          name: google-image_install_initialize-dev
          context: orb-publishing
          requires:
            - install-dev
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /integration-.*/

      - gcp-cli/use_google_image_and_initialize_cli:
          name: google-image_install_initialize-master
          context: orb-publishing
          requires:
            - install-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/

      - dev-promote-prod:
          context: orb-publishing
          requires:
            - install_initialize-master
            - google-image_install_initialize-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/
