version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.4

filters: &filters
  tags:
    only: /.*/

install-initialize_requires: &install-initialize_requires
  [install-default, install-google, install-machine]

prod-deploy_requires: &prod-deploy_requires
  [install_initialize-default, install_initialize-google, install_initialize-machine]

install-post-steps: &install-post-steps
  [run: gcloud --version]

jobs:
  install:
    parameters:
      executor:
        type: executor
      version:
        type: string

    executor: <<parameters.executor>>

    steps:
      - gcp-cli/install:
          version: <<parameters.version>>

  install-alpine:
    parameters:
      version:
        type: string

    executor: "alpine"
    
    steps:
      - run:
          name: Install curl
          command: apk add curl
      - gcp-cli/install:
          version: latest

executors:
  alpine:
    docker:
      - image: python:3.7-alpine

workflows:
  test-deploy:
    jobs:
      - install: 
          matrix:
            parameters:
              executor: [ gcp-cli/default, gcp-cli/google, gcp-cli/machine ]
              version: [ latest, 371.0.0, 402.0.0]
          context: orb-publisher
          post-steps: *install-post-steps
          filters: *filters
      - install-alpine: 
          matrix:
            parameters:
              version: [ latest, 371.0.0, 402.0.0]
          context: orb-publisher
          pre-steps:
            - run: |
                touch "$BASH_ENV"
                . "$BASH_ENV"
          post-steps: *install-post-steps
          filters: *filters
      # run job with all executors
      # - gcp-cli/install_and_initialize_cli:
      #     name: install_initialize-default
      #     context: orb-publisher
      #     requires: *install-initialize_requires
      #     post-steps: *install-post-steps
      #     filters: *filters
      # - gcp-cli/install_and_initialize_cli:
      #     name: install_initialize-google
      #     executor: gcp-cli/google
      #     context: orb-publisher
      #     requires: *install-initialize_requires
      #     post-steps: *install-post-steps
      #     filters: *filters
      # - gcp-cli/install_and_initialize_cli:
      #     name: install_initialize-machine
      #     executor: gcp-cli/machine
      #     context: orb-publisher
      #     requires: *install-initialize_requires
      #     post-steps: *install-post-steps
      #     filters: *filters

      - orb-tools/pack:
          filters: *filters

      - orb-tools/publish:
          orb-name: circleci/gcp-cli
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            # - install_initialize-default
            # - install_initialize-google
            # - install_initialize-machine
            - orb-tools/pack
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/