version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.4

filters: &filters
  tags:
    only: /.*/

install-initialize_requires: &install-initialize_requires
  [install-default, install-google, install-machine]

prod-deploy_requires: &prod-deploy_requires
  [install_initialize-default, install_initialize-google, install_initialize-machine]

install-post-steps: &install-post-steps
  [run: gcloud --version]

jobs:
  # default executor
  install-default:
    executor: gcp-cli/default
    steps:
      - gcp-cli/install

  # google cloud image
  install-google:
    executor: gcp-cli/google
    steps:
      - gcp-cli/install

  # machine executor
  install-machine:
    executor: gcp-cli/machine
    steps:
      - gcp-cli/install

workflows:
  test-deploy:
    jobs:
      - install-default:
          context: orb-publisher
          post-steps: *install-post-steps
          filters: *filters
      - install-google:
          context: orb-publisher
          post-steps: *install-post-steps
          filters: *filters
      - install-machine:
          context: orb-publisher
          post-steps: *install-post-steps
          filters: *filters

      # run job with all executors
      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-default
          context: orb-publisher
          requires: *install-initialize_requires
          post-steps: *install-post-steps
          filters: *filters
      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-google
          executor: gcp-cli/google
          context: orb-publisher
          requires: *install-initialize_requires
          post-steps: *install-post-steps
          filters: *filters
      - gcp-cli/install_and_initialize_cli:
          name: install_initialize-machine
          executor: gcp-cli/machine
          context: orb-publisher
          requires: *install-initialize_requires
          post-steps: *install-post-steps
          filters: *filters

      - orb-tools/pack:
          filters: *filters

      - orb-tools/publish:
          orb-name: circleci/gcp-cli
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - install-default
            - install-google
            - install-machine
            - install_initialize-default
            - install_initialize-google
            - install_initialize-machine
            - orb-tools/pack
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/