description: >
  A debian based docker container to use when running the gcloud CLI

parameters:
  python-version:
    type: string
    default: "2.7"
    description: >
      What version of Python? For full options, see
      https://hub.docker.com/r/circleci/python/tags

  debian-release:
    type: enum
    enum: ["stretch", "jessie"]
    default: "stretch"
    description: >
      Which Debian release?

docker:
  - image: circleci/python:<<parameters.python-version>>-<<parameters.debian-release>>
